name: 'Create CNAME Record'
description: 'This action will create a CNAME record in the found yaml file'
inputs:
  environment:
    required: true
    description: 'Environment to search for the DNS Zone'
  zone_name: 
    required: true
    description: 'DNS Zone name to search for'
  record_name:
    required: true
    description: 'Record name for new entry'
  record_value:
    required: true
    description: 'Record value for new entry'
  record_ttl:
    required: true
    description: 'Record time to live for new entry'

runs:
  using: "composite"
  steps:
    - name: read from file
      id: readOriginalFile
      uses: mikefarah/yq@v4.44.1
      with:
          cmd: yq '.cname' 'example.yaml'

    - name: show yq result
      shell: bash
      run: echo Result is "${{ steps.readOriginalFile.outputs.result }}"

    - name: update file
      uses: mikefarah/yq@v4.44.1
      with:
        cmd: yq -i '.cname += {"name":"${{ github.event.inputs.record_name }}", "ttl":${{ github.event.inputs.record_ttl }}, "record":"${{ github.event.inputs.record_value }}"} | .cname[].name style="double" | .cname[].record style="double"' example.yaml

    - name: read from updated file
      id: readUpdatedFile
      uses: mikefarah/yq@v4.44.1
      with:
          cmd: yq '.cname' 'example.yaml'

    - name: show yq result
      shell: bash
      run: echo Result is "${{ steps.readUpdatedFile.outputs.result }}"
