apiVersion: v2
appVersion: '1.0'
description: A Helm chart for labs-mfox-nodejs App
name: labs-mfox-nodejs
home: https://github.com/hmcts/labs-mfox-nodejs
version: 0.0.1
dependencies:
  - name: nodejs
    version: 2.4.14
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
