name: 'Create an A Record'
description: 'This action will create an A record in the found yaml file'
inputs:
  environment:
    required: true
    description: 'Environment to search for the DNS Zone'
  zone_name: 
    required: true
    description: 'DNS Zone name to search for'
  record_name:
    required: true
    description: 'Record name for new entry'
  record_value:
    required: true
    description: 'Record value for new entry'
  record_ttl:
    required: true
    description: 'Record time to live for new entry'

runs:
  using: "composite"
  steps:
    - name: read from file
      id: readOriginalFile
      uses: mikefarah/yq@v4.44.1
      with:
          cmd: yq '.A' 'example.yaml'

    - name: show yq result
      shell: bash
      run: echo Result is "${{ steps.readOriginalFile.outputs.result }}"

    - name: update file
      uses: mikefarah/yq@v4.44.1
      with:
        cmd: yq -i '.A += {"name":"${{ github.event.inputs.record_name }}", "ttl":"${{ github.event.inputs.record_ttl }}", "record":["${{ github.event.inputs.record_value }}"]} | .A[].ttl style="" | .A[].name style="double" | .A[].record style="double"' example.yaml

    - name: read from updated file
      id: readUpdatedFile
      uses: mikefarah/yq@v4.44.1
      with:
          cmd: yq '.A' 'example.yaml'

    - name: show yq result
      shell: bash
      run: echo Result is "${{ steps.readUpdatedFile.outputs.result }}"
