name: Backstage Test

on:
  workflow_dispatch:
    inputs:
      dns_zone:
        type: string
        description: ""
      record_name:
        type: string
        description: ""
      record_value:
        type: string
        description: ""
      record_ttl:
        type: number
        description: ""
      record_type:
        type: string
        description: ""
      environments:
        type: string
        description: ""
        default: "missing"
      cft_sds:
        type: string
        description: ""

jobs:
  build:
    runs-on: ubuntu-latest
    # outputs:
    #   matrix-environments: ${{ steps.set-matrix-environments.outputs.matrix-environments }}
    steps:
    - uses: actions/checkout@v4
    # - id: set-matrix-environments
    #   run: |
    #     environments="${{ inputs.environments }}"
    #     echo "matrix-environments=[\"${environments//', '/\",\"}\"]" >> $GITHUB_OUTPUT
    
    - name: Set Branch Name
      run: echo "BACKSTAGE_BRANCH_NAME=${{ inputs.dns_zone }}_${{ inputs.record_name }}_${{ inputs.record_value }}_${{ inputs.cft_sds }}" >> $GITHUB_ENV
    
    - name: git create branch
      run: |
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git checkout -b $BACKSTAGE_BRANCH_NAME

    - name: Print Inputs
      run: |
        echo "DNS Zone Name: ${{ inputs.dns_zone }}"
        echo "DNS Record Name: ${{ inputs.record_name }}"
        echo "DNS Record Value: ${{ inputs.record_value }}"
        echo "DNS Record TTL: ${{ inputs.record_ttl }}"
        echo "Environment: ${{ inputs.environments }}"
        echo "Platform: ${{ inputs.cft_sds }}"

    - name: Create sample.yaml
      run: |
        touch example.yaml
        echo "--- 
        A:
          - name: \"ctscmail\"
            ttl: 3600
            record:
              -  \"51.140.180.140 \"
        
        cname:
          - name:  \"_1fc88e03b87b33fb04a3b1c5978e80b8 \"
            ttl: 900
            record:  \"3FED4C626334D6135F1258241ADBBF36.F6728027F74DAF3E336958B894F24534.ma5er55rQa0HPM55O5Fq.comodoca.com \"
          - name:  \"reformscan \"
            ttl: 60
            record:  \"hmcts-sbox-gufqadefbjgbhkhv.z01.azurefd.net\" " > example.yaml

    - name: Add new A Record
      if: ${{ inputs.record_type == 'A' }}
      uses: "./.github/actions/aRecord"
      with:
        zone_name: ${{ inputs.dns_zone }}
        record_name: ${{ inputs.record_name }}
        record_value: ${{ inputs.record_value }}
        record_ttl: ${{ inputs.record_ttl }}
        environment: ${{ inputs.environments }}
        
    - name: Add new CNAME Record
      if: ${{ inputs.record_type == 'CNAME' }}
      uses: "./.github/actions/cnameRecord"
      with:
        zone_name: ${{ inputs.dns_zone }}
        record_name: ${{ inputs.record_name }}
        record_value: ${{ inputs.record_value }}
        record_ttl: ${{ inputs.record_ttl }}
        environment: ${{ inputs.environments }}

    - name: Workspace
      run: ls ${{ github.workspace }}

    - name: git commit branch
      run: |
        git add .
        git commit -m "Backstage DNS workflow - Adding updated files to commit"
        git push -u origin $BACKSTAGE_BRANCH_NAME

    - name: create pull request
      run: gh pr create -B master -H $BACKSTAGE_BRANCH_NAME --title 'Create new ${{ inputs.record_name }} record in ${{ inputs.dns_zone }}' --body 'Created by Backstage'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
