name: Backstage Test

on:
  workflow_dispatch:
    inputs:
      dns_zone:
        type: string
        description: ""
      record_name:
        type: string
        description: ""
      record_value:
        type: string
        description: ""
      record_ttl:
        type: string
        description: ""
      environments:
        type: string
        description: ""
        default: "missing"
      cft_sds:
        type: string
        description: ""

jobs:
  build:
    runs-on: ubuntu-latest
    # outputs:
    #   matrix-environments: ${{ steps.set-matrix-environments.outputs.matrix-environments }}
    steps:
    - uses: actions/checkout@v4
    # - id: set-matrix-environments
    #   run: |
    #     environments="${{ github.event.inputs.environments }}"
    #     echo "matrix-environments=[\"${environments//', '/\",\"}\"]" >> $GITHUB_OUTPUT
    
    - name: Set Branch Name
      run: echo "BACKSTAGE_BRANCH_NAME=${{ github.event.inputs.dns_zone }}_${{ github.event.inputs.record_name }}_${{ github.event.inputs.record_value }}_${{ github.event.inputs.cft_sds }}" >> $GITHUB_ENV
    
    - name: Print Branch Name
      run: echo $BACKSTAGE_BRANCH_NAME

    - name: git create branch
      run: |
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git checkout -b $BACKSTAGE_BRANCH_NAME

    - name: Print Inputs
      run: |
        echo "DNS Zone Name: ${{ github.event.inputs.dns_zone }}"
        echo "DNS Record Name: ${{ github.event.inputs.record_name }}"
        echo "DNS Record Value: ${{ github.event.inputs.record_value }}"
        echo "DNS Record TTL: ${{ github.event.inputs.record_ttl }}"
        echo "Environment: ${{ github.event.inputs.environments }}"
        echo "Platform: ${{ github.event.inputs.cft_sds }}"

    - name: Create example.yaml
      run: |
        touch example.yaml
        echo "dnsZoneName: ${{ github.event.inputs.dns_zone }}
        dnsRecordName: ${{ github.event.inputs.record_name }}
        dnsRecordValue: ${{ github.event.inputs.record_value }}
        dnsRecordTTL: ${{ github.event.inputs.record_ttl }}
        environment: ${{ github.event.inputs.environments }}
        platform: ${{ github.event.inputs.cft_sds }}" > example.yaml

              
    - name: read from file
      uses: mikefarah/yq@v4.44.1
      with:
          cmd: yq '.dnsRecordName' 'example.yaml'

    - name: update file
      uses: mikefarah/yq@v4.44.1
      with:
          cmd: yq '.dnsRecordName = "YQ updated me"' 'example.yaml'

    - name: read from updated file
      uses: mikefarah/yq@v4.44.1
      with:
          cmd: yq '.dnsRecordName' 'example.yaml'

    - name: Workspace
      run: ls ${{ github.workspace }}

    - name: git commit branch
      run: |
        git add .
        git commit -m "Backstage DNS workflow - Adding updated files to commit"
        git push -u origin $BACKSTAGE_BRANCH_NAME

    - name: create pull request
      run: gh pr create -B master -H $BACKSTAGE_BRANCH_NAME --title 'Create new ${{ github.event.inputs.record_name }} record in ${{ github.event.inputs.dns_zone }}' --body 'Created by Backstage'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
